# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      PACT_CLI_IMG: pactfoundation/pact-cli:0.12.3.0
      PACT_BROKER_URL: localhost:9292
    strategy:
      fail-fast: false
      matrix:
        service: [welcome-member-email-service, special-membership-service, credit-score-service]

    steps:
      - uses: actions/checkout@v3
      - name: "Honeycomb: setup recording"
        uses: honeycombio/gha-buildevents@brookesargent.multi-job-support
        with:
          # Required: a Honeycomb API key - needed to send traces.
          #           this must be set in your GitHub repository under Settings > Secrets > Actions
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
          # Required: the Honeycomb dataset to send traces to.
          dataset: gha-buildevents_integration
          # Required: the job status, this will be used in the post section and sent
          #           as status of the trace. Must always be ${{ job.status }}.
          job-status: ${{ job.status }}
          gh-token: ${{ secrets.GH_PAT }}

          # Optional: this should only be used in combination with matrix builds. Set
          # this to a value uniquely describing each matrix configuration.
          matrix-key: ${{ matrix.service }}

      - name: Start dependencies with docker-compose
        run: docker-compose -f pact-tools/pact-broker/docker-compose.yml up -d

      - name: Set up JDK
        uses: actions/setup-java@v3.4.1
        with:
          java-version: 14
          distribution: 'adopt'

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Start build step
        run: |
          STEP_ID=service_build-${{ matrix.service }}
          echo "STEP_ID=${STEP_ID}" >> $GITHUB_ENV
          echo "STEP_START=$(date +%s)" >> $GITHUB_ENV
      - name: Build service
        run: |
          .github/scripts/${{ matrix.service }}-build.sh
      - name: "Honeycomb: Finalise service span"
        run: buildevents step $TRACE_ID $STEP_ID $STEP_START $STEP_ID
        if: success() || failure()

      - name: Stop dependencies with docker-compose
        run: docker-compose -f pact-tools/pact-broker/docker-compose.yml down
        if: always()