# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACT_CLI_IMG: pactfoundation/pact-cli:0.12.3.0
      PACT_BROKER_URL: localhost:9292
    steps:
      - uses: actions/checkout@v3
      - name: "Honeycomb: setup recording"
        uses: honeycombio/gha-buildevents@v1
        with:
          # Required: a Honeycomb API key - needed to send traces.
          #   must be set in your GitHub repository under Settings > Secrets > Actions
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}

          # Required: the Honeycomb dataset to send traces to
          dataset: buildevents
          # Required: the job status, this will be used in the post section and sent
          #   as status of the trace. Must always be ${{ job.status }}.
          job-status: ${{ job.status }}

          # Optional: this should only be used in combination with matrix builds. Set
          # this to a value uniquely describing each matrix configuration.
          # matrix-key: ${{ matrix.service }}
